### ISSUE TITLE
Feature Request: Admin accessing players sethomes

### ISSUE THREAD

**Issue by TinyMandalorian** [Ale32bit/Solstice#1]
Would it be possible to implement a feature where say a owner/admim has the permission to access other players /homes via a command like /home (playername) (home name) or like /homeother (player) (homename)

**Comment by Ale32bit** [comment]
`/home <player> <home>` could be confusing, so I think `/homeother <player> <home>` looks better; will also add `/homes [player]` to list the player's homes (with clickable texts to teleport without typing the command).
