### ISSUE TITLE
Issue using /homeother command

### ISSUE THREAD

**Issue by TinyMandalorian** [Ale32bit/Solstice#2]
![image](https://github.com/user-attachments/assets/38cb6da3-8a01-4bf0-b0b4-998bc94f18e6)

**Comment by Ale32bit** [comment]
`/homeother` requires the `solstice.command.homeother` permission node (or OP level 2), can you check you have it granted?

**Comment by TinyMandalorian** [comment]
> `/homeother` requires the `solstice.command.homeother` permission node (or OP level 2), can you check you have it granted?

Im pretty sure I got it as im opped and have granted myself every permission using luckperms *

**Comment by TinyMandalorian** [comment]
![image](https://github.com/user-attachments/assets/f3c88f2f-aa40-4755-83f9-54adce7ca17e)

**Comment by Ale32bit** [comment]
Can you run `/lp verbose on`, then run the command `/homeother` and send the output here?
You can turn off the log spam by running `/lp verbose off`.

**Comment by TinyMandalorian** [comment]
![image](https://github.com/user-attachments/assets/a111d4a7-95d1-4a33-b7ff-bd2b948d236f)

**Comment by Ale32bit** [comment]
Make sure you have exactly `solstice.command.homeother`, this is the permission for the command `/homeother`.

**Comment by TinyMandalorian** [comment]
![image](https://github.com/user-attachments/assets/6e1c135d-58af-4a8d-bfc3-76b0a444dbf5)
nope

**Comment by Ale32bit** [comment]
Found the issue, expect an update in the next 10 minutes

**Comment by TinyMandalorian** [comment]
thanks

**Comment by Ale32bit** [comment]
Update published.
