### ISSUE TITLE
Tp to spawn on death

### ISSUE THREAD

**Issue by TinyMandalorian** [Ale32bit/Solstice#9]
Could you add a feature for teleporting the player to /spawn on death right now the reason im asking for this is im using multiworld which allows me to use multiple worlds so i can use one for spawn and one for survival and i can set the spawn and teleport fine but when i die i stay in the overworld and when i try to set the vanilla spawn to the other world it doesnt allow me but if it were possible to send the player to /spawn on death that would work.

**Comment by TinyMandalorian** [comment]
also in the most recent update did you remove the chat module?

**Comment by Ale32bit** [comment]
I will publish the next update when other stuff is ready, you can try it anyway by downloading the build here: https://github.com/Ale32bit/Solstice/actions/runs/12536715754/artifacts/2369479263
